FEDORA6-120: Introduce a "usingDocuteamModel" in fcrepo-indexing-triplestore
docuteam/fcrepo-camel-toolbox pull request #2
Opened 2024-12-05 12:28 UTC by decdocuteam

- The new module dcouteam-fcrepo-camel-ext contains the change to the Sparql requestes for delete and update to use the docuteam model.
- Introduce the new properties triplestore.using.docuteam.model to modify the behaviour of the triplestore indexer in case of update. By default it is set to true. Setting this properties to false revert to the standard behaviour.
- Add a DocuteamRouterTest test for the custom behaviour.

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3932

# Additional Notes:
We some additional integration test for the custom behavior.

2025-03-17 10:33 UTC, basimar requested changes
Hi Vincent
I now finished the review. Just some grammatical changes in the comments and a question. I can confirm that the code for the deletion statements is the same as in my original PR.

2025-03-17 10:33 UTC, basimar commented on docuteam-fcrepo-camel-ext/pom.xml
> +    <description>This extension introduce custom behaviour tied to the docuteam model. The goal is to support hash URI
This extension introduce -> This extension introduce**s**

2025-03-17 10:33 UTC, basimar commented on docuteam-fcrepo-camel-ext/src/main/java/ch/docuteam/fcrepo/camel/processor/DocuteamProcessorUtils.java
> + * This class provide a deleteWhere util method that is tied to the
This class provide a deleteWhere util method that is tied to the docuteam datamodel compare to the standard one provided in ProcessorUtils
->
This class provides a deleteWhere util method that is tied to the docuteam data model compared to the standard one provided in ProcessorUtils

2025-03-17 10:33 UTC, basimar commented on docuteam-fcrepo-camel-ext/src/main/java/ch/docuteam/fcrepo/camel/processor/DocuteamSparqlDeleteProcessor.java
> + * This implementation used the docuteam model and was derived from the
This implementation used -> This implementation use**s**

2025-03-17 10:33 UTC, basimar commented on docuteam-fcrepo-camel-ext/src/main/java/ch/docuteam/fcrepo/camel/processor/DocuteamSparqlDeleteProcessor.java
> +        in.setBody("update=" + encode(deleteWhere(subject, namedGraph), StandardCharsets.UTF_8));
I assume "UTF-8" (from the old code) and StandardCharsets.UTF_8 are equivalent?

2025-03-17 10:33 UTC, basimar commented on docuteam-fcrepo-camel-ext/src/main/java/ch/docuteam/fcrepo/camel/processor/DocuteamSparqlUpdateProcessor.java
> +                insertData(serializedGraph.toString("UTF-8"), namedGraph), "UTF-8"));
Also use StandardCharsets.UTF_8 here?

2025-03-21 11:53 UTC, decdocuteam commented on docuteam-fcrepo-camel-ext/src/main/java/ch/docuteam/fcrepo/camel/processor/DocuteamSparqlDeleteProcessor.java
> +        in.setBody("update=" + encode(deleteWhere(subject, namedGraph), StandardCharsets.UTF_8));
Yes they are.

2025-03-21 12:34 UTC, decdocuteam commented on docuteam-fcrepo-camel-ext/pom.xml
> +    <description>This extension introduce custom behaviour tied to the docuteam model. The goal is to support hash URI
done

2025-03-21 12:34 UTC, decdocuteam commented on docuteam-fcrepo-camel-ext/src/main/java/ch/docuteam/fcrepo/camel/processor/DocuteamProcessorUtils.java
> + * This class provide a deleteWhere util method that is tied to the
done

2025-03-21 12:34 UTC, decdocuteam commented on docuteam-fcrepo-camel-ext/src/main/java/ch/docuteam/fcrepo/camel/processor/DocuteamSparqlUpdateProcessor.java
> +                insertData(serializedGraph.toString("UTF-8"), namedGraph), "UTF-8"));
done

2025-03-25 09:00 UTC, merged